#!/bin/bash

site=`realpath $1`
if [[ ! -e $site ]]; then
    echo "No such site $1"
    exit 1
fi
echo "Enabling $site..."
pushd /etc/apache2/sites-enabled
sudo ln -s $site
ls -l
popd
sudo apache2ctl restart
